name: Run Python Script and Upload Animation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Updated to the latest version

    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to the latest version
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib

    - name: Install ffmpeg
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg

    - name: Check ffmpeg installation
      run: ffmpeg -version

    - name: Run script
      run: python scripts/script1.py  # Run the script to generate the animation

    - name: Upload Mandelbrot animation artifact
      uses: actions/upload-artifact@v4  # Updated to the latest version
      with:
        name: mandelbrot-animation
        path: scripts/mandelbrot_animation.mp4  # Ensure the correct path to the video file
