name: Run Python Script and Upload Animation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy matplotlib

    - name: Install ffmpeg
      run: sudo apt-get install ffmpeg

    - name: Run script
      run: python scripts/script1.py  # Run the script

    - name: Upload Mandelbrot animation artifact
      uses: actions/upload-artifact@v3
      with:
        name: mandelbrot-animation
        path: mandelbrot_animation.mp4  # Upload the video as an artifact
